# Generated by Django 4.2.7 on 2024-06-29 07:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author_github",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="layout",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
