# Generated by Django 4.2.7 on 2024-07-12 05:54
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_executivemember_date_joined"),
        ("blog", "0003_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.executivemember",
            ),
        ),
    ]
