# Generated by Django 4.2.7 on 2024-08-02 07:55
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_executivemember_date_joined"),
        ("blog", "0008_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.executivemember",
            ),
            preserve_default=False,
        ),
    ]
