# Generated by Django 4.2.7 on 2024-10-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_github',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
