# Generated by Django 5.1.3 on 2025-02-12 14:31
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_executivemember_date_joined"),
        ("blog", "0010_alter_post_author_github"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts_approved",
                to="accounts.executivemember",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="ready_for_approval",
            field=models.BooleanField(default=False),
        ),
    ]
