# Generated by Django 5.1.3 on 2025-02-12 17:32
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_post_approved_post_approved_at_post_approver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(null=True),
        ),
    ]
