# Generated by Django 5.1.3 on 2025-02-25 11:21
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_post_published_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
