# Generated by Django 5.1.3 on 2025-09-26 11:26
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_post_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="approved_at",
        ),
    ]
