# Generated by Django 4.2.7 on 2024-01-16 04:31
import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_email_alter_user_phone_no_executivemember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executivemember",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 16, 10, 1, 4, 787196),
                verbose_name="Date Joined",
            ),
        ),
    ]
