# Generated by Django 4.2.7 on 2024-01-19 18:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_email_alter_user_phone_no_executivemember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executivemember",
            name="date_joined",
            field=models.DateField(verbose_name="Date Joined"),
        ),
        migrations.AlterField(
            model_name="executivemember",
            name="github",
            field=models.CharField(
                blank=True, max_length=39, null=True, verbose_name="GitHub Username"
            ),
        ),
    ]
