# Generated by Django 4.2.7 on 2024-01-19 16:59
import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_email_alter_user_phone_no_executivemember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executivemember",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 19, 22, 29, 26, 499748),
                verbose_name="Date Joined",
            ),
        ),
        migrations.AlterField(
            model_name="executivemember",
            name="github",
            field=models.CharField(
                blank=True, max_length=39, null=True, verbose_name="GitHub Username"
            ),
        ),
    ]
