# Generated by Django 4.2.7 on 2024-02-29 12:37
import datetime

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_sig_society_sigs"),
        ("accounts", "0002_alter_user_email_alter_user_phone_no_executivemember"),
    ]

    operations = [
        migrations.AddField(
            model_name="executivemember",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="execmember/profile_picture"
            ),
        ),
        migrations.AlterField(
            model_name="executivemember",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 29, 18, 7, 3, 350454),
                verbose_name="Date Joined",
            ),
        ),
        migrations.AlterField(
            model_name="executivemember",
            name="github",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="GitHub Username"
            ),
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post", models.CharField(max_length=100)),
                ("term_start", models.DateField(default=django.utils.timezone.now)),
                ("term_end", models.DateField(null=True)),
                (
                    "sig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="config.sig"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "faculties",
            },
        ),
        migrations.CreateModel(
            name="Core",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post", models.CharField(max_length=100)),
                ("term_start", models.DateField(default=django.utils.timezone.now)),
                ("term_end", models.DateField(null=True)),
                (
                    "sig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="config.sig"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
