# Generated by Django 4.2.4 on 2024-01-24 13:40
import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_executivemember_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executivemember",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 24, 19, 10, 0, 912845),
                verbose_name="Date Joined",
            ),
        ),
    ]
