# Generated by Django 4.2.7 on 2024-03-21 05:30
import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_executivemember_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executivemember",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 21, 5, 30, 54, 960770, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Joined",
            ),
        ),
        migrations.AlterField(
            model_name="executivemember",
            name="github",
            field=models.CharField(
                blank=True, max_length=39, null=True, verbose_name="GitHub Username"
            ),
        ),
    ]
