# Generated by Django 4.2.7 on 2024-05-16 15:44
import datetime

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    replaces = [
        ("accounts", "0006_executivemember_profile_picture_and_more"),
        (
            "accounts",
            "0007_post_remove_core_sig_core_society_faculty_is_execom_and_more",
        ),
        ("accounts", "0008_post_is_sac_alter_executivemember_date_joined"),
        ("accounts", "0009_faculty_linkedin_faculty_society_and_more"),
        ("accounts", "0010_remove_faculty_is_execom_and_more"),
        ("accounts", "0011_faculty_profile_picture_and_more"),
    ]

    dependencies = [
        ("accounts", "0005_alter_executivemember_date_joined_and_more"),
        ("config", "0004_sig_society_sigs"),
    ]

    operations = [
        migrations.AddField(
            model_name="executivemember",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="accounts/executivemember/profile_picture",
            ),
        ),
        migrations.AlterField(
            model_name="executivemember",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date Joined"
            ),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("is_execom", models.BooleanField(default=False)),
                ("is_sac", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="executivemember",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 16, 8, 12, 19, 155417, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Joined",
            ),
        ),
        migrations.CreateModel(
            name="Core",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.post"
                    ),
                ),
                ("term_start", models.DateField()),
                ("term_end", models.DateField()),
                (
                    "executivemember",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.executivemember",
                    ),
                ),
                (
                    "society",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="config.society",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="executivemember",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 16, 12, 40, 58, 735459, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Joined",
            ),
        ),
        migrations.AlterField(
            model_name="executivemember",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 16, 13, 27, 39, 346181, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Joined",
            ),
        ),
        migrations.AlterField(
            model_name="executivemember",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 16, 13, 35, 45, 55285, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Joined",
            ),
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.post"
                    ),
                ),
                ("term_start", models.DateField()),
                ("term_end", models.DateField()),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "sig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="config.sig"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linkedin",
                    models.URLField(
                        blank=True, null=True, verbose_name="Linkedin Profile URL"
                    ),
                ),
                (
                    "society",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="config.society",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="accounts/faculty/profile_picture",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "faculties",
            },
        ),
        migrations.AlterField(
            model_name="executivemember",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 16, 13, 39, 13, 997822, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Joined",
            ),
        ),
    ]
