# Generated by Django 4.2.7 on 2024-11-06 20:34
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_executivemember_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivemember',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='Date Joined'),
        ),
    ]
