# Generated by Django 4.2.10 on 2024-03-13 17:40
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_core_user_core_executivemember_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="post",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Branch Counselor", "Branch Counselor"),
                    ("CIS Faculty Advisor", "CIS Faculty Advisor"),
                    ("CompSoc Faculty Advisor", "CompSoc Faculty Advisor"),
                    ("CAS Faculty Advisor", "CAS Faculty Advisor"),
                    ("SPS Faculty Advisor", "SPS Faculty Advisor"),
                    (
                        "Photonic Society Faculty Advisor",
                        "Photonic Society Faculty Advisor",
                    ),
                    ("WIE Faculty Advisor", "WIE Faculty Advisor"),
                    ("IAS Faculty Advisor", "IAS Faculty Advisor"),
                    ("SIGHT Chair", "SIGHT Chair"),
                    ("RAS Faculty Advisor", "RAS Faculty Advisor"),
                    ("GRSS Faculty Advisor", "GRSS Faculty Advisor"),
                ],
                max_length=100,
            ),
        ),
    ]
