# Generated by Django 4.2.7 on 2024-05-16 08:12
import datetime

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_sig_society_sigs"),
        ("accounts", "0006_executivemember_profile_picture_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("is_execom", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="core",
            name="sig",
        ),
        migrations.AddField(
            model_name="core",
            name="society",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="config.society",
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="is_execom",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="executivemember",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 16, 8, 12, 19, 155417, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Joined",
            ),
        ),
        migrations.AlterField(
            model_name="core",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.post"
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.post"
            ),
        ),
    ]
