# Generated by Django 4.2.7 on 2024-05-16 12:40
import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0007_post_remove_core_sig_core_society_faculty_is_execom_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_sac",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="executivemember",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 16, 12, 40, 58, 735459, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Joined",
            ),
        ),
    ]
