# Generated by Django 5.1.3 on 2025-01-22 12:30

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivemember',
            name='hide_github',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='executivemember',
            name='hide_linkedin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='accounts/profile/pics', validators=[accounts.validators.validate_image]),
        ),
    ]
