# Generated by Django 4.2.7 on 2024-05-16 13:27
import datetime

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_sig_society_sigs"),
        ("accounts", "0008_post_is_sac_alter_executivemember_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="linkedin",
            field=models.URLField(
                blank=True, null=True, verbose_name="Linkedin Profile URL"
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="society",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="config.society",
            ),
        ),
        migrations.AlterField(
            model_name="executivemember",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 16, 13, 27, 39, 346181, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Joined",
            ),
        ),
    ]
