# Generated by Django 5.1.3 on 2025-01-28 17:29
import constants
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="executivemember",
            name="hide_github",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="executivemember",
            name="hide_linkedin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="accounts/profile/pics",
                validators=[constants.validate_image],
            ),
        ),
    ]
