# Generated by Django 5.1.3 on 2025-02-25 11:21
from django.db import migrations
from django.db import models

import corpus.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_executivemember_hide_github_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="profile/pics",
                validators=[corpus.validators.validate_image],
            ),
        ),
    ]
