# Generated by Django 4.2.7 on 2024-05-16 13:35
import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_faculty_linkedin_faculty_society_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faculty",
            name="is_execom",
        ),
        migrations.AlterField(
            model_name="executivemember",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 16, 13, 35, 45, 55285, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Joined",
            ),
        ),
    ]
