# Generated by Django 5.1.3 on 2025-03-26 10:37

import accounts.models
import corpus.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_executivemember_hide_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=accounts.models.User.get_upload_path, validators=[corpus.validators.validate_image]),
        ),
    ]
