# Generated by Django 5.1.3 on 2025-08-24 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_executivemember_hide_github_and_more'),
        ('config', '0004_sig_society_sigs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('is_execom', models.BooleanField(default=False)),
                ('is_sac', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='executivemember',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/executivemember/profile_picture'),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='accounts/faculty/profile_picture')),
                ('website', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin Profile URL')),
                ('term_start', models.DateField()),
                ('term_end', models.DateField()),
                ('sig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.sig')),
                ('society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.society')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.post')),
            ],
            options={
                'verbose_name_plural': 'faculties',
            },
        ),
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_start', models.DateField()),
                ('term_end', models.DateField()),
                ('executivemember', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.executivemember')),
                ('society', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.society')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.post')),
            ],
        ),
    ]
