# Generated by Django 4.2.7 on 2024-05-16 13:39
import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_remove_faculty_is_execom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="accounts/faculty/profile_picture"
            ),
        ),
        migrations.AlterField(
            model_name="executivemember",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 16, 13, 39, 13, 997822, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date Joined",
            ),
        ),
    ]
