# Generated by Django 5.1.3 on 2025-11-04 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_executivemember_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivemember',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 4, 17, 7, 43, 638281, tzinfo=datetime.timezone.utc), verbose_name='Date Joined'),
        ),
    ]
