# Generated by Django 5.1.3 on 2025-12-12 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_executivemember_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivemember',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 12, 12, 4, 56, 52590, tzinfo=datetime.timezone.utc), verbose_name='Date Joined'),
        ),
    ]
