# Generated by Django 4.2.7 on 2024-03-21 05:30
import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_alter_executivemember_date_joined_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("abstract", models.TextField()),
                (
                    "thumbnail",
                    models.ImageField(upload_to="virtual_expo/reports/thumbnails"),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                ("ready_for_approval", models.BooleanField(default=False)),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.executivemember",
                    ),
                ),
                (
                    "report_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_expo.reporttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.executivemember",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_expo.report",
                    ),
                ),
            ],
            options={
                "unique_together": {("report", "member")},
            },
        ),
    ]
