# Generated by Django 4.2.7 on 2024-03-19 13:49
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("abstract", models.CharField(max_length=200)),
                (
                    "thumbnail",
                    models.ImageField(upload_to="virtual_expo/reports/thumbnails"),
                ),
                ("content", django_ckeditor_5.fields.CKEditor5Field()),
                ("year", models.PositiveSmallIntegerField()),
                ("ready_for_approval", models.BooleanField(default=False)),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.executivemember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReportType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ReportMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.executivemember",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_expo.report",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="report",
            name="report_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="virtual_expo.reporttype",
            ),
        ),
    ]
