version: '3.1'

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U corpus"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - corpus_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    expose:
      - ${ADMINER_PORT}
    env_file:
      - .env
    networks:
      - corpus_network

  corpus:
    build: corpus
    command: /corpus/start.sh
    restart: always
    expose:
      - ${DJANGO_BACKEND_PORT}
    networks:
      - corpus_network
    volumes:
      - static_files:/corpus/static
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - ENVIRONMENT=PRODUCTION

  nginx:
    build: nginx
    restart: always
    depends_on:
      - corpus
      - postgres
    networks:
      - corpus_network
    ports:
      - "80:80"
    volumes:
      - static_files:/etc/nginx/staticfiles
    env_file:
      - .env

networks:
  corpus_network:

volumes:
  static_files:
  postgres_data:
