# Generated by Django 4.2.4 on 2023-12-10 14:14
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbedathonUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_nitk", models.BooleanField(default=True)),
                (
                    "college_name",
                    models.CharField(
                        default="National Institute of Technology Karnataka",
                        max_length=200,
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[("B", "B.Tech."), ("M", "M.Tech."), ("P", "PhD")],
                        max_length=1,
                    ),
                ),
                ("year", models.IntegerField()),
                ("branch", models.CharField(max_length=200)),
                ("ieee_member", models.BooleanField(default=False)),
                ("ieee_membership_no", models.BigIntegerField(blank=True, null=True)),
                ("cass_member", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
