# Generated by Django 4.2.4 on 2023-12-16 14:18
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("embedathon", "0002_team_invite_embedathonuser_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="payment_status",
            field=models.CharField(
                choices=[("E", "Exempt"), ("U", "Fee Not Paid"), ("P", "Fee Paid")],
                default="U",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="embedathonuser",
            name="course",
            field=models.CharField(
                choices=[
                    ("B", "B.Tech."),
                    ("E", "B.E."),
                    ("S", "B.Sc."),
                    ("O", "Other undergraduate degree"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="embedathonuser",
            name="year",
            field=models.CharField(
                choices=[("1", "1st Year"), ("2", "2nd Year")], max_length=1
            ),
        ),
    ]
