# Generated by Django 4.2.4 on 2023-12-21 17:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("embedathon", "0003_team_payment_status_alter_embedathonuser_course_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("url_link", models.URLField(blank=True, null=True)),
                (
                    "url_link_text",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
