# Generated by Django 4.2.7 on 2024-10-19 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_executivemember_date_joined'),
        ('config', '0004_sig_society_sigs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('registration_url', models.URLField(unique=True)),
                ('meeting_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('location', models.CharField(max_length=32)),
                ('category', models.CharField(choices=[('KSS', 'KSS'), ('COMPETITION', 'Competition'), ('EXPERT_LECTURE', 'Expert Lecture'), ('WORKSHOP', 'Workshop'), ('HACKATHON', 'Hackathon')])),
                ('visibility', models.CharField(blank=True, choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')])),
                ('created_at', models.DateTimeField()),
                ('poc', models.ManyToManyField(related_name='events', to='accounts.executivemember')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.society')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('exec_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.executivemember')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('resources', models.JSONField(null=True)),
                ('student_turnout', models.IntegerField()),
                ('faculty_turnout', models.IntegerField(null=True)),
                ('photo_1', models.ImageField(upload_to='')),
                ('photo_2', models.ImageField(upload_to='')),
                ('iic_report_url', models.URLField(null=True)),
                ('dsw_report_url', models.URLField(null=True)),
                ('created_at', models.DateTimeField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.URLField()),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
