# Generated by Django 4.2.4 on 2023-12-03 11:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_society_description_society_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_name", models.CharField(max_length=200)),
                ("module_enabled", models.BooleanField(default=False)),
                ("module_config", models.JSONField()),
            ],
        ),
    ]
