# Generated by Django 4.2.3 on 2023-12-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_moduleconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CompSoc', 'CompSoc'), ('Diode', 'Diode'), ('Piston', 'Piston'), ('WiE', 'WiE'), ('SIGHT', 'SIGHT')], max_length=10, unique=True, verbose_name='Name')),
                ('aboutus', models.CharField(verbose_name='AboutUs')),
                ('whatwedo', models.CharField(verbose_name='WhatWeDo')),
            ],
            options={
                'verbose_name': 'SIG',
                'verbose_name_plural': 'SIGs',
            },
        ),
    ]
