# Generated by Django 5.1.3 on 2025-12-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_sig_society_sigs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sig',
            name='color',
            field=models.CharField(blank=True, default='#6b7280', help_text='Hex color code, e.g., #fba418', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='sig',
            name='sig_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='SIG Image'),
        ),
        migrations.CreateModel(
            name='AlumniLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Alumni Organization Name')),
                ('image', models.ImageField(upload_to='img/alumni_logos/', verbose_name='Logo Image')),
                ('sigs', models.ManyToManyField(related_name='alumni_logos', to='config.sig')),
            ],
            options={
                'verbose_name': 'Alumni Logo',
                'verbose_name_plural': 'Alumni Logos',
            },
        ),
    ]
