# Generated by Django 5.1.3 on 2025-08-25 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_sig_society_sigs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sig',
            name='sig_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='SIG Image'),
        ),
        migrations.CreateModel(
            name='AlumniLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Alumni Organization Name')),
                ('image', models.ImageField(upload_to='img/alumni_logos/', verbose_name='Logo Image')),
                ('sig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_logos', to='config.sig')),
            ],
            options={
                'verbose_name': 'Alumni Logo',
                'verbose_name_plural': 'Alumni Logos',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/events/', verbose_name='Event Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('sig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='config.sig')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['order'],
            },
        ),
    ]
