# Generated by Django 5.1.3 on 2025-10-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_sig_society_sigs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sig',
            name='color',
            field=models.CharField(default='#6b7280', help_text='Hex color code, e.g., #fba418', max_length=7),
        ),
    ]
