# Generated by Django 4.2.4 on 2023-12-18 16:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_sig"),
    ]

    operations = [
        migrations.AddField(
            model_name="sig",
            name="sigimg",
            field=models.ImageField(
                blank=True, null=True, upload_to="img/logo/", verbose_name="SIGImage"
            ),
        ),
    ]
