# Generated by Django 4.2.4 on 2023-12-19 06:24
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_sig_sigimg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sig",
            name="aboutus",
        ),
        migrations.RemoveField(
            model_name="sig",
            name="sigimg",
        ),
        migrations.RemoveField(
            model_name="sig",
            name="whatwedo",
        ),
        migrations.AddField(
            model_name="sig",
            name="about_us",
            field=models.CharField(default="", verbose_name="About Us"),
        ),
        migrations.AddField(
            model_name="sig",
            name="sig_img",
            field=models.ImageField(
                blank=True, null=True, upload_to="img/logo/", verbose_name="SIG Image"
            ),
        ),
        migrations.AddField(
            model_name="sig",
            name="what_we_do",
            field=models.CharField(default="", verbose_name="What We Do"),
        ),
        migrations.AlterField(
            model_name="sig",
            name="name",
            field=models.CharField(max_length=10, unique=True, verbose_name="Name"),
        ),
    ]
