# Generated by Django 5.1.3 on 2025-08-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_sig_sig_image_alumnilogo_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='sig',
            name='event_stats',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sig',
            name='member_stats',
            field=models.TextField(default=''),
        ),
    ]
