# Generated by Django 5.1.3 on 2025-08-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_sig_event_stats_sig_member_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Event Image'),
        ),
    ]
