# Generated by Django 4.2.4 on 2023-12-19 06:33
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0006_remove_sig_aboutus_remove_sig_sigimg_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sig",
            old_name="about_us",
            new_name="about",
        ),
        migrations.RemoveField(
            model_name="sig",
            name="sig_img",
        ),
    ]
