# Generated by Django 5.1.3 on 2025-08-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnilogo',
            name='sig',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sig',
        ),
        migrations.AddField(
            model_name='alumnilogo',
            name='sigs',
            field=models.ManyToManyField(related_name='alumni_logos', to='config.sig'),
        ),
        migrations.AddField(
            model_name='event',
            name='sigs',
            field=models.ManyToManyField(related_name='event', to='config.sig'),
        ),
    ]
