# Generated by Django 5.1.3 on 2025-08-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_remove_alumnilogo_sig_remove_event_sig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sigs',
            field=models.ManyToManyField(related_name='events', to='config.sig'),
        ),
    ]
