# Generated by Django 5.1.3 on 2025-11-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_alter_event_sigs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sig',
            name='event_stats',
        ),
        migrations.RemoveField(
            model_name='sig',
            name='member_stats',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
