# Generated by Django 4.2.4 on 2024-02-18 14:33
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("url_link", models.URLField(blank=True, null=True)),
                (
                    "url_link_text",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("A", "All Robotrix Users"),
                            ("P", "Paid Teams"),
                            ("U", "Unpaid Teams"),
                            ("N", "Registered for Robotrix but no team"),
                            ("NI", "Not Registered for Robotrix"),
                        ],
                        default="A",
                        max_length=2,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RobotrixUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_nitk", models.BooleanField(default=True)),
                (
                    "college_name",
                    models.CharField(
                        default="National Institute of Technology Karnataka",
                        max_length=200,
                    ),
                ),
                ("roll_no", models.CharField(blank=True, max_length=8, null=True)),
                ("ieee_member", models.BooleanField(default=False)),
                ("ieee_membership_no", models.BigIntegerField(blank=True, null=True)),
                (
                    "phone_no",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Phone Number"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=200)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("E", "Exempt"),
                            ("U", "Fee Not Paid"),
                            ("P", "Fee Paid"),
                        ],
                        default="U",
                        max_length=1,
                    ),
                ),
                (
                    "team_leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leader",
                        to="robotrix.robotrixuser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="robotrixuser",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team",
                to="robotrix.team",
            ),
        ),
        migrations.AddField(
            model_name="robotrixuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invite_email", models.EmailField(max_length=254)),
                (
                    "inviting_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_to_team",
                        to="robotrix.team",
                    ),
                ),
            ],
        ),
    ]
