# Generated by Django 5.1.3 on 2025-05-23 17:32
import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0009_executivemember_hide_github_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("abstract", models.TextField()),
                ("thumbnail", models.ImageField(upload_to="smp/programs/thumbnails")),
                ("description", ckeditor_uploader.fields.RichTextUploadingField()),
                ("year", models.PositiveSmallIntegerField()),
                ("hide_program", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "upload_type",
                    models.CharField(
                        choices=[
                            ("Assignment", "Assignment"),
                            ("Resource", "Resource"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="smp.program"
                    ),
                ),
                (
                    "upload_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.executivemember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="smp.upload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgramMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_type",
                    models.CharField(
                        choices=[("Mentor", "Mentor"), ("Mentee", "Mentee")],
                        max_length=10,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="smp.program"
                    ),
                ),
            ],
            options={
                "unique_together": {("program", "member")},
            },
        ),
    ]
