# Generated by Django 5.1.3 on 2025-05-24 05:39
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("smp", "0002_submission_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
