# Generated by Django 5.1.3 on 2025-05-25 05:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smp', '0003_remove_title_db_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='hide_program',
            field=models.BooleanField(default=True),
        ),
    ]
