# Generated by Django 4.2.7 on 2024-01-15 08:43
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("url_link", models.URLField(blank=True, null=True)),
                (
                    "url_link_text",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("A", "All Electrika Users"),
                            ("T", "All Electrika Teams"),
                            ("N", "Registered for Electrika but no team"),
                        ],
                        default="A",
                        max_length=2,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ElectrikaUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_nitk", models.BooleanField(default=True)),
                (
                    "college_name",
                    models.CharField(
                        default="National Institute of Technology Karnataka",
                        max_length=200,
                    ),
                ),
                ("roll_no", models.CharField(blank=True, max_length=8, null=True)),
                ("ieee_member", models.BooleanField(default=False)),
                ("ieee_membership_no", models.BigIntegerField(blank=True, null=True)),
                ("to_be_teamed_up", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=200)),
                (
                    "team_leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leader",
                        to="electrika.electrikauser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invite_email", models.EmailField(max_length=254)),
                (
                    "inviting_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_to_team",
                        to="electrika.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="electrikauser",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team",
                to="electrika.team",
            ),
        ),
        migrations.AddField(
            model_name="electrikauser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
