# Generated by Django 4.2.7 on 2024-03-16 11:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Senior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("url_id", models.CharField(max_length=5)),
                ("email_id", models.EmailField(max_length=50, null=True)),
                ("coming_farewell", models.BooleanField(default=False)),
            ],
        ),
    ]
