# Generated by Django 4.2.7 on 2024-01-19 16:59
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Title")),
                ("date", models.DateField(verbose_name="Date of Achievement")),
                (
                    "url",
                    models.URLField(blank=True, null=True, verbose_name="Related URL"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Related User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("GSOC", "Google Summer of Code"),
                            ("IAS SRFP", "IAS Summer Research Fellowship Program"),
                            ("SB", "Student Branch Award"),
                        ],
                        max_length=32,
                        verbose_name="Tag",
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.achievement",
                        verbose_name="Achievement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, verbose_name="Title")),
                ("date", models.DateField(verbose_name="Publish Date")),
                ("url", models.URLField(verbose_name="URL")),
                ("authors", models.CharField(max_length=256, verbose_name="Authors")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Related User",
                    ),
                ),
            ],
        ),
    ]
