# Generated by Django 4.2.7 on 2023-12-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impulse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impulseuser',
            name='is_member2',
        ),
        migrations.RemoveField(
            model_name='impulseuser',
            name='member2_college_name',
        ),
        migrations.RemoveField(
            model_name='impulseuser',
            name='member2_email',
        ),
        migrations.RemoveField(
            model_name='impulseuser',
            name='member2_from_nitk',
        ),
        migrations.RemoveField(
            model_name='impulseuser',
            name='member2_ieee_member',
        ),
        migrations.RemoveField(
            model_name='impulseuser',
            name='member2_ieee_membership_no',
        ),
        migrations.RemoveField(
            model_name='impulseuser',
            name='member2_name',
        ),
        migrations.RemoveField(
            model_name='impulseuser',
            name='member2_phone',
        ),
        migrations.RemoveField(
            model_name='impulseuser',
            name='member2_roll_no',
        ),
        migrations.AddField(
            model_name='team',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='member_college_name',
            field=models.CharField(default='National Institute of Technology Karnataka', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='member_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='member_from_nitk',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='member_ieee_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='member_ieee_membership_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='member_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='member_phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='member_roll_no',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='impulseuser',
            name='roll_no',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
