# Generated by Django 4.2.7 on 2024-01-03 06:06
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("impulse", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="payment_proof",
        ),
    ]
