# Generated by Django 4.2.7 on 2024-02-04 15:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("skyward_expedition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seuser",
            name="college_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
