# Generated by Django 4.2.7 on 2024-02-13 11:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("skyward_expedition", "0002_seuser_college_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="seuser",
            name="degree",
            field=models.CharField(
                default=1, help_text="Degree Pursuing", max_length=200
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seuser",
            name="ieee_member",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seuser",
            name="ieee_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="seuser",
            name="nitk_participant",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seuser",
            name="roll_number",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="seuser",
            name="year_of_study",
            field=models.IntegerField(default=1, help_text="Year of Study"),
            preserve_default=False,
        ),
    ]
