# Generated by Django 4.2.7 on 2024-03-04 04:10
import django.db.models.deletion
from django.db import migrations
from django.db import models

import corpus.validators


class Migration(migrations.Migration):

    dependencies = [
        (
            "skyward_expedition",
            "0003_seuser_degree_seuser_ieee_member_seuser_ieee_number_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="skyward_expedition/submissions",
                        validators=[
                            corpus.validators.FileValidator(
                                content_types=(
                                    "application/zip",
                                    "application/x-rar-compressed",
                                    "application/octet-stream",
                                ),
                                max_size=10485760,
                            )
                        ],
                        verbose_name="Submission File",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skyward_expedition.team",
                    ),
                ),
            ],
        ),
    ]
