# Generated by Django 5.1.3 on 2025-08-13 12:59
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("config", "0004_sig_society_sigs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("page_link", models.URLField(blank=True, max_length=400, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("archive_event", models.BooleanField(default=False)),
                ("show_in_recent", models.BooleanField(default=False)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="newsletter/events/thumbnails"
                    ),
                ),
                (
                    "sigs",
                    models.ManyToManyField(
                        blank=True, null=True, related_name="events", to="config.sig"
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
