# Generated by Django 5.1.3 on 2024-12-07 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('event', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='newspost', to='events.event')),
            ],
        ),
    ]
