# Generated by Django 5.1.3 on 2024-12-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'verbose_name': 'News Post', 'verbose_name_plural': 'News Posts'},
        ),
        migrations.AddField(
            model_name='newspost',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/newsletter'),
        ),
    ]
