# Generated by Django 5.1.3 on 2026-10-03 12:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_event_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='archive_event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='show_in_recent',
        ),
        migrations.AddField(
            model_name='event',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status_override',
            field=models.CharField(blank=True, choices=[('', 'Automatic (by end date)'), ('recent', 'Force Recent'), ('archived', 'Force Archived')], default='', help_text='Leave Automatic unless this event must be pinned to a section.', max_length=10),
        ),
    ]
