# Generated by Django 5.1.3 on 2024-12-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_newspost_options_newspost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='new',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
